version: "3.9"
services:
  cli:
    image: korcekj/ml-fraud-detection:<tag>
    depends_on:
      - api
    environment:
      - MS_DISTANCE_URL=<msdistance url>
    volumes:
      - <data dir path>:/home/cli_user/<dir>
      - <visuals dir path>:/home/cli_user/<dir>
      - <models dir path>:/home/cli_user/<dir>
    stdin_open: true
    tty: true
  api:
    image: korcekj/ms-distance:<tag>
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=<mongodb uri>
      - MONGO_DB=<mongodb name>
      - DM_API_KEY=<distancematrix api key>
      - GC_API_KEY=<geocode api key>